# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Science of Soul
tagline:             
url:                 http://scienceofsoul.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Prashanth
  url:               https://twitter.com/scienceofsoul1
  email:             prashanth@scienceofsoul.net

# Custom vars
version:             3.0.0
github:
  repo:              https://github.com/scienceofsoul/scienceofsoul.github.io

# Gems
gems:
- jekyll-paginate

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
